#!/usr/bin/env python3
"""Agent Readiness Scorer — takes a URL and scores how AI-agent-friendly it is."""

import json
import sys
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

console = Console()
HEADERS = {"User-Agent": "AgentReadinessBot/1.0 (checking agent-readiness)"}
TIMEOUT = 10


def get(url):
    try:
        r = requests.get(url, headers=HEADERS, timeout=TIMEOUT, allow_redirects=True)
        return r
    except Exception:
        return None


def check_llms_txt(origin):
    r = get(f"{origin}/llms.txt")
    if r and r.status_code == 200 and len(r.text.strip()) > 0:
        return True, "Found", r.text.strip()[:300]
    return False, "Missing", None


def check_robots_txt(origin):
    r = get(f"{origin}/robots.txt")
    if not r or r.status_code != 200:
        return False, "robots.txt not found"
    text = r.text.lower()
    agents = ["gptbot", "claudebot", "anthropic-ai", "googleother", "bingbot"]
    found = [a for a in agents if a in text]
    if found:
        return True, f"AI agents mentioned: {', '.join(found)}"
    return False, "No AI agent rules (GPTBot, ClaudeBot, etc.)"


def check_sitemap(origin):
    for path in ["/sitemap.xml", "/sitemap_index.xml"]:
        r = get(f"{origin}{path}")
        if r and r.status_code == 200:
            return True, f"Found at {path}"
    return False, "No sitemap.xml found"


def check_json_ld(soup):
    scripts = soup.find_all("script", type="application/ld+json")
    if scripts:
        try:
            data = json.loads(scripts[0].string)
            kind = data.get("@type", "unknown") if isinstance(data, dict) else "array"
            return True, f"Found ({kind})", data
        except Exception:
            return True, "Found (malformed JSON)", None
    return False, "No JSON-LD structured data", None


def check_opengraph(soup):
    og_tags = soup.find_all("meta", property=lambda v: v and v.startswith("og:"))
    if og_tags:
        found = [t.get("property") for t in og_tags[:5]]
        return True, f"Found: {', '.join(found)}"
    return False, "No OpenGraph tags"


def check_meta(soup):
    title = soup.find("title")
    desc = soup.find("meta", attrs={"name": "description"})
    has_title = bool(title and title.text.strip())
    has_desc = bool(desc and desc.get("content", "").strip())
    if has_title and has_desc:
        return True, f'Title: "{title.text.strip()[:60]}"'
    parts = []
    if not has_title:
        parts.append("missing title")
    if not has_desc:
        parts.append("missing meta description")
    return False, "Incomplete: " + ", ".join(parts)


def check_canonical(soup):
    link = soup.find("link", rel="canonical")
    if link and link.get("href"):
        return True, f'href="{link["href"]}"'
    return False, "No canonical URL"


def check_clean_content(url):
    jina_url = f"https://r.jina.ai/{url}"
    r = get(jina_url)
    if r and r.status_code == 200 and len(r.text.strip()) > 100:
        word_count = len(r.text.split())
        return True, f"{word_count} words extracted cleanly", r.text[:500]
    return False, "Could not extract clean content via Jina Reader", None


def generate_llms_txt(url, origin, soup, json_ld, jina_content, sitemap_ok):
    title = ""
    desc = ""

    title_tag = soup.find("title")
    if title_tag:
        title = title_tag.text.strip()

    desc_tag = soup.find("meta", attrs={"name": "description"})
    if desc_tag:
        desc = desc_tag.get("content", "").strip()

    og_desc = soup.find("meta", property="og:description")
    if og_desc and not desc:
        desc = og_desc.get("content", "").strip()

    lines = [f"# {title or origin}", ""]
    if desc:
        lines += [f"> {desc}", ""]

    lines += [f"## About", f"- URL: {url}", ""]

    if json_ld and isinstance(json_ld, dict):
        if json_ld.get("description"):
            lines += [json_ld["description"][:300], ""]

    if sitemap_ok:
        lines += ["## Sitemap", f"- {origin}/sitemap.xml", ""]

    if jina_content:
        summary = " ".join(jina_content.split()[:80])
        lines += ["## Summary", summary, ""]

    lines += [
        "## Notes",
        "- This llms.txt was auto-generated by AgentReadiness PoC",
        "- Edit to add canonical product descriptions, key pages, and agent instructions",
    ]

    return "\n".join(lines)


def score_and_report(url):
    parsed = urlparse(url)
    origin = f"{parsed.scheme}://{parsed.netloc}"

    console.print(f"\n[bold]Scanning:[/bold] {url}\n")

    # Fetch main page
    r = get(url)
    if not r or r.status_code >= 400:
        console.print(f"[red]Could not fetch {url} (status: {r.status_code if r else 'error'})[/red]")
        sys.exit(1)

    soup = BeautifulSoup(r.text, "html.parser")

    # Run all checks
    checks = {}
    checks["llms_txt"] = check_llms_txt(origin)
    checks["robots_txt"] = check_robots_txt(origin)
    checks["sitemap"] = check_sitemap(origin)
    checks["json_ld"] = check_json_ld(soup)
    checks["opengraph"] = check_opengraph(soup)
    checks["meta"] = check_meta(soup)
    checks["canonical"] = check_canonical(soup)
    checks["clean_content"] = check_clean_content(url)

    weights = {
        "llms_txt": 25,
        "robots_txt": 10,
        "sitemap": 10,
        "json_ld": 15,
        "opengraph": 10,
        "meta": 10,
        "canonical": 5,
        "clean_content": 15,
    }

    labels = {
        "llms_txt": "/llms.txt file",
        "robots_txt": "robots.txt AI rules",
        "sitemap": "sitemap.xml",
        "json_ld": "JSON-LD structured data",
        "opengraph": "OpenGraph tags",
        "meta": "Title + meta description",
        "canonical": "Canonical URL",
        "clean_content": "Clean content (Jina Reader)",
    }

    # Build score
    score = sum(weights[k] for k, (ok, *_) in checks.items() if ok)

    # Render table
    table = Table(box=box.ROUNDED, show_header=True, header_style="bold cyan")
    table.add_column("Check", style="bold", width=28)
    table.add_column("Points", justify="right", width=8)
    table.add_column("Status", width=50)

    for key, (ok, detail, *_) in checks.items():
        pts = weights[key]
        status_icon = "[green]PASS[/green]" if ok else "[red]FAIL[/red]"
        earned = f"[green]+{pts}[/green]" if ok else f"[red] 0[/red]"
        table.add_row(labels[key], earned, f"{status_icon}  {detail}")

    console.print(table)

    # Score panel
    color = "green" if score >= 70 else "yellow" if score >= 40 else "red"
    grade = "Excellent" if score >= 80 else "Good" if score >= 60 else "Needs work" if score >= 40 else "Poor"
    console.print(Panel(
        f"[bold {color}]{score}/100[/bold {color}]  —  {grade}",
        title="Agent Readiness Score",
        border_style=color,
    ))

    # Generate llms.txt
    json_ld_data = checks["json_ld"][2] if len(checks["json_ld"]) > 2 else None
    jina_text = checks["clean_content"][2] if len(checks["clean_content"]) > 2 else None
    sitemap_ok = checks["sitemap"][0]

    llms_txt = generate_llms_txt(url, origin, soup, json_ld_data, jina_text, sitemap_ok)

    console.print(Panel(
        llms_txt,
        title="[bold]Draft /llms.txt[/bold]  (save this to your domain root)",
        border_style="blue",
    ))

    # Recommendations
    fails = [(labels[k], weights[k]) for k, (ok, *_) in checks.items() if not ok]
    if fails:
        fails.sort(key=lambda x: -x[1])
        console.print("\n[bold yellow]Top recommendations (highest impact first):[/bold yellow]")
        for label, pts in fails:
            console.print(f"  [yellow]•[/yellow] Add [bold]{label}[/bold] (+{pts} pts)")

    console.print()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        console.print("Usage: python agent_readiness.py <url>")
        console.print("Example: python agent_readiness.py https://stripe.com")
        sys.exit(1)

    url = sys.argv[1]
    if not url.startswith("http"):
        url = "https://" + url

    score_and_report(url)
